import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Template from './models/Template.js';
import User from './models/User.js';

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Template.deleteMany({});
    console.log('Cleared existing templates');

    // Create admin user
    const existingAdmin = await User.findOne({ role: 'admin' });
    if (!existingAdmin) {
      await User.create({
        name: 'Admin',
        email: 'admin@guestinvitation.com',
        phone: '+919999999999',
        password: 'Admin@123',
        role: 'admin',
      });
      console.log('Admin user created');
    }

    // Template definitions for all festive categories
    const templates = [
      // === GANPATI TEMPLATES ===
      {
        name: 'Ganesh Chaturthi Grand',
        slug: 'ganesh-chaturthi-01',
        category: 'ganpati',
        previewImage: '/templates/ganpati-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 0,
        tags: ['ganpati', 'ganesh', 'chaturthi', 'bappa', 'festive'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#FF6B35', secondary: '#FFD700', background: '#FFF8F0', text: '#333333' },
        order: 1,
      },
      {
        name: 'Welcome Bappa',
        slug: 'welcome-bappa',
        category: 'ganpati',
        previewImage: '/templates/ganpati-02.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 0,
        tags: ['ganpati', 'welcome', 'bappa', 'aagman'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#E65100', secondary: '#FFC107', background: '#FFF3E0', text: '#333333' },
        order: 2,
      },
      {
        name: 'Golden Makhar',
        slug: 'golden-makhar',
        category: 'ganpati',
        previewImage: '/templates/ganpati-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 99,
        tags: ['ganpati', 'golden', 'makhar', 'premium'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#B8860B', secondary: '#FFD700', background: '#FFFEF0', text: '#2C1810' },
        order: 3,
      },
      {
        name: 'Shubh Aagman',
        slug: 'shubh-aagman',
        category: 'ganpati',
        previewImage: '/templates/ganpati-04.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['ganpati', 'aagman', 'shubh'],
        language: 'hindi',
        hasVideo: false,
        themeColors: { primary: '#D84315', secondary: '#FFB74D', background: '#FBE9E7', text: '#333333' },
        order: 4,
      },
      {
        name: 'Modak Mandir',
        slug: 'modak-mandir',
        category: 'ganpati',
        previewImage: '/templates/ganpati-05.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 149,
        tags: ['ganpati', 'modak', 'mandir'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#FF8F00', secondary: '#FFE082', background: '#FFF8E1', text: '#333333' },
        order: 5,
      },
      {
        name: 'Dhol Tasha Ganpati',
        slug: 'dhol-tasha-ganpati',
        category: 'ganpati',
        previewImage: '/templates/ganpati-06.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 199,
        tags: ['ganpati', 'dhol', 'tasha', 'music'],
        language: 'marathi',
        hasVideo: true,
        themeColors: { primary: '#C62828', secondary: '#FFD54F', background: '#FFEBEE', text: '#333333' },
        order: 6,
      },
      {
        name: 'Sandhya Aarti',
        slug: 'sandhya-aarti',
        category: 'ganpati',
        previewImage: '/templates/ganpati-07.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['ganpati', 'aarti', 'evening'],
        language: 'marathi',
        hasVideo: true,
        themeColors: { primary: '#E65100', secondary: '#FFCC80', background: '#FFF3E0', text: '#333333' },
        order: 7,
      },
      {
        name: 'Sinhasan Ganpati',
        slug: 'sinhasan-ganpati',
        category: 'ganpati',
        previewImage: '/templates/ganpati-08.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 249,
        tags: ['ganpati', 'sinhasan', 'royal', 'premium'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#6A1B9A', secondary: '#FFD700', background: '#F3E5F5', text: '#333333' },
        order: 8,
      },

      // === JANMASHTAMI TEMPLATES ===
      {
        name: 'Bal Gopal',
        slug: 'bal-gopal',
        category: 'janmashtami',
        previewImage: '/templates/janmashtami-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 0,
        tags: ['janmashtami', 'krishna', 'gopal', 'baby'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#1565C0', secondary: '#FFD54F', background: '#E3F2FD', text: '#333333' },
        order: 9,
      },
      {
        name: 'Aala Re Aala',
        slug: 'aala-re-aala',
        category: 'janmashtami',
        previewImage: '/templates/janmashtami-02.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['janmashtami', 'krishna', 'celebration'],
        language: 'marathi',
        hasVideo: true,
        themeColors: { primary: '#283593', secondary: '#FFC107', background: '#E8EAF6', text: '#333333' },
        order: 10,
      },
      {
        name: 'Dahi Handi',
        slug: 'dahi-handi',
        category: 'janmashtami',
        previewImage: '/templates/janmashtami-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 99,
        tags: ['janmashtami', 'dahi', 'handi', 'govinda'],
        language: 'marathi',
        hasVideo: false,
        themeColors: { primary: '#0277BD', secondary: '#FFB300', background: '#E1F5FE', text: '#333333' },
        order: 11,
      },

      // === NAVRATRI TEMPLATES ===
      {
        name: 'Navratri Grand',
        slug: 'navratri-01',
        category: 'navratri',
        previewImage: '/templates/navratri-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 0,
        tags: ['navratri', 'durga', 'garba', 'dandiya'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#C62828', secondary: '#FFD700', background: '#FFEBEE', text: '#333333' },
        order: 12,
      },
      {
        name: 'Garba Night',
        slug: 'garba-night',
        category: 'navratri',
        previewImage: '/templates/navratri-02.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 149,
        tags: ['navratri', 'garba', 'night', 'dance'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#AD1457', secondary: '#FFE082', background: '#FCE4EC', text: '#333333' },
        order: 13,
      },
      {
        name: 'Dandiya Raas',
        slug: 'dandiya-raas',
        category: 'navratri',
        previewImage: '/templates/navratri-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 199,
        tags: ['navratri', 'dandiya', 'raas'],
        language: 'hindi',
        hasVideo: false,
        themeColors: { primary: '#E65100', secondary: '#FFD740', background: '#FFF3E0', text: '#333333' },
        order: 14,
      },

      // === WEDDING TEMPLATES ===
      {
        name: 'Royal Wedding',
        slug: 'royal-wedding',
        category: 'wedding',
        previewImage: '/templates/wedding-01.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 299,
        tags: ['wedding', 'royal', 'shaadi', 'marriage'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#800020', secondary: '#FFD700', background: '#FFF8F0', text: '#333333' },
        order: 15,
      },
      {
        name: 'Maroon Darbar',
        slug: 'maroon-darbar',
        category: 'wedding',
        previewImage: '/templates/wedding-02.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 249,
        tags: ['wedding', 'maroon', 'darbar', 'traditional'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#880E4F', secondary: '#FFC107', background: '#FCE4EC', text: '#333333' },
        order: 16,
      },
      {
        name: 'Pastel Bliss',
        slug: 'pastel-bliss',
        category: 'wedding',
        previewImage: '/templates/wedding-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 199,
        tags: ['wedding', 'pastel', 'modern', 'elegant'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#F48FB1', secondary: '#CE93D8', background: '#FFF0F5', text: '#555555' },
        order: 17,
      },
      {
        name: 'Bengal Terracotta',
        slug: 'bengal-terracotta',
        category: 'wedding',
        previewImage: '/templates/wedding-04.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 299,
        tags: ['wedding', 'bengali', 'terracotta', 'traditional'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#BF360C', secondary: '#FFAB91', background: '#FBE9E7', text: '#333333' },
        order: 18,
      },
      {
        name: 'Marigold Mandap',
        slug: 'marigold-mandap',
        category: 'wedding',
        previewImage: '/templates/wedding-05.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 99,
        tags: ['wedding', 'marigold', 'mandap', 'flowers'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#EF6C00', secondary: '#FFD54F', background: '#FFF8E1', text: '#333333' },
        order: 19,
      },

      // === BIRTHDAY TEMPLATES ===
      {
        name: 'Pastel Dream Birthday',
        slug: 'pastel-dream-birthday',
        category: 'birthday',
        previewImage: '/templates/birthday-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 0,
        tags: ['birthday', 'pastel', 'celebration', 'party'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#7B1FA2', secondary: '#FF80AB', background: '#F3E5F5', text: '#333333' },
        order: 20,
      },
      {
        name: 'Starlit Blue',
        slug: 'starlit-blue',
        category: 'birthday',
        previewImage: '/templates/birthday-02.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['birthday', 'blue', 'stars', 'night'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#1A237E', secondary: '#FFD740', background: '#E8EAF6', text: '#333333' },
        order: 21,
      },
      {
        name: 'Blush Balloons',
        slug: 'blush-balloons',
        category: 'birthday',
        previewImage: '/templates/birthday-03.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['birthday', 'balloons', 'blush', 'kids'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#EC407A', secondary: '#F8BBD0', background: '#FFF0F5', text: '#333333' },
        order: 22,
      },
      {
        name: 'Golden Celebration',
        slug: 'golden-celebration',
        category: 'birthday',
        previewImage: '/templates/birthday-04.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 99,
        tags: ['birthday', 'golden', 'celebration', 'premium'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#F57F17', secondary: '#FFD700', background: '#FFFDE7', text: '#333333' },
        order: 23,
      },

      // === GRIHA PRAVESH TEMPLATES ===
      {
        name: 'Vastu Torana',
        slug: 'vastu-torana',
        category: 'griha-pravesh',
        previewImage: '/templates/grihapravesh-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['griha-pravesh', 'housewarming', 'vastu', 'new-home'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#2E7D32', secondary: '#FFD54F', background: '#E8F5E9', text: '#333333' },
        order: 24,
      },
      {
        name: 'Rangoli Threshold',
        slug: 'rangoli-threshold',
        category: 'griha-pravesh',
        previewImage: '/templates/grihapravesh-02.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['griha-pravesh', 'rangoli', 'threshold'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#00695C', secondary: '#FF8A65', background: '#E0F2F1', text: '#333333' },
        order: 25,
      },
      {
        name: 'Shubh Griha Aagman',
        slug: 'shubh-griha-aagman',
        category: 'griha-pravesh',
        previewImage: '/templates/grihapravesh-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 99,
        tags: ['griha-pravesh', 'shubh', 'aagman', 'hindi'],
        language: 'hindi',
        hasVideo: false,
        themeColors: { primary: '#E65100', secondary: '#FFCC80', background: '#FFF3E0', text: '#333333' },
        order: 26,
      },

      // === ENGAGEMENT TEMPLATES ===
      {
        name: 'Garden Promise',
        slug: 'garden-promise',
        category: 'engagement',
        previewImage: '/templates/engagement-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 99,
        tags: ['engagement', 'garden', 'ring', 'promise'],
        language: 'english',
        hasVideo: false,
        themeColors: { primary: '#C2185B', secondary: '#F8BBD0', background: '#FFF0F5', text: '#333333' },
        order: 27,
      },
      {
        name: 'Rose & Ring',
        slug: 'rose-and-ring',
        category: 'engagement',
        previewImage: '/templates/engagement-02.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 149,
        tags: ['engagement', 'rose', 'ring', 'romantic'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#D81B60', secondary: '#FFD700', background: '#FCE4EC', text: '#333333' },
        order: 28,
      },
      {
        name: 'Sagan Sampanna',
        slug: 'sagan-sampanna',
        category: 'engagement',
        previewImage: '/templates/engagement-03.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 199,
        tags: ['engagement', 'sagan', 'traditional', 'hindi'],
        language: 'hindi',
        hasVideo: false,
        themeColors: { primary: '#BF360C', secondary: '#FFAB91', background: '#FBE9E7', text: '#333333' },
        order: 29,
      },

      // === HALDI TEMPLATES ===
      {
        name: 'Turmeric Glow',
        slug: 'turmeric-glow',
        category: 'haldi',
        previewImage: '/templates/haldi-01.jpg',
        backgroundImage: '',
        isPremium: false,
        price: 49,
        tags: ['haldi', 'turmeric', 'yellow', 'wedding'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#F9A825', secondary: '#FFD54F', background: '#FFFDE7', text: '#333333' },
        order: 30,
      },
      {
        name: 'Marigold Havan',
        slug: 'marigold-havan',
        category: 'haldi',
        previewImage: '/templates/haldi-02.jpg',
        backgroundImage: '',
        isPremium: true,
        price: 99,
        tags: ['haldi', 'marigold', 'havan', 'ceremony'],
        language: 'english',
        hasVideo: true,
        themeColors: { primary: '#FF8F00', secondary: '#FFE082', background: '#FFF8E1', text: '#333333' },
        order: 31,
      },
    ];

    await Template.insertMany(templates);
    console.log(`${templates.length} templates seeded successfully`);

    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedData();
